# frozen_string_literal: true

module IssueDigest
  class IssueResolver
    # recipient_modes: a Set of personalization categories (:assignees,
    # :authors, :watchers, :broad) describing *why* this user is a recipient.
    # When present (and not :broad), the issue scope is narrowed to the issues
    # that match those relationships. nil keeps the legacy behavior (only the
    # explicit filter_* flags personalize the scope).
    def initialize(rule, user: nil, recipient_modes: nil)
      @rule = rule
      @user = user
      @recipient_modes = recipient_modes
    end

    # Returns a scoped relation of issues visible to @user matching the rule's filters.
    # When user is nil (used for candidate scope in RecipientResolver), returns
    # Issue.visible (system-wide visible) scoped to the project — no per-user filter.
    def resolve
      build_scope
    rescue StandardError => e
      Rails.logger.error "[IssueDigest] Rule ##{@rule.id}: issue resolution failed: #{e.class}: #{e.message}"
      Issue.none
    end

    # Base scope without visibility applied — used by RecipientResolver to find
    # candidate assignees/watchers without loading issues into memory.
    def base_scope
      if @user
        # Per-user delivery path: respect Redmine's full visibility rules.
        # Issue.visible already joins :project internally; do not double-join.
        scope = Issue.visible(@user)
      else
        # Candidate-scope path (recipient discovery, rake context).
        # Issue.visible(User.current) resolves to AnonymousUser in rake, which
        # sees only public projects — private projects return zero issues, making
        # assignees/authors/watchers modes silently produce 0 recipients.
        # Skip visibility here; per-recipient filtering is enforced in #resolve
        # (called with a real user) at delivery time.
        scope = Issue.joins(:project)
                     .where("#{Project.table_name}.status != ?", Project::STATUS_ARCHIVED)
      end
      if @rule.include_subprojects?
        scope = scope.where(
          "#{Project.table_name}.lft >= ? AND #{Project.table_name}.rgt <= ?",
          @rule.project.lft, @rule.project.rgt
        )
      else
        scope = scope.where("#{Issue.table_name}.project_id = ?", @rule.project.id)
      end
      scope
    end

    private

    def build_scope
      scope = base_scope
      scope = apply_match_filters(scope)
      scope = apply_since_last_run_filter(scope)
      scope = apply_personalization_filters(scope)
      adapter = IssueDigest::QueryAdapter.new(@rule)
      scope   = adapter.apply_to(scope)
      @query_adapter_warning = adapter.warning
      scope = scope.order(Arel.sql(portable_due_date_order_sql))
      scope
    end

    public

    # Returns any warning generated by the QueryAdapter (e.g. deleted query).
    # Only populated after #resolve or #base_scope is called via build_scope.
    def query_adapter_warning
      @query_adapter_warning
    end

    private

    # Inclusion ("Include …") filters are additive: every checked option ADDS
    # its matching issues to the digest, so they are OR-combined into a single
    # WHERE clause. Status options (open/closed/overdue/due_soon) need the
    # statuses join; the recency options (updated/created) reference the issues
    # table only. Leaving everything unchecked returns all project issues.
    #
    # Narrowing happens elsewhere (since_last_run_created/updated, saved query,
    # personalization) and is AND-combined on top of this result.
    def apply_match_filters(scope)
      status_conditions = []
      status_conditions << open_condition     if @rule.include_open?
      status_conditions << closed_condition   if @rule.include_closed?
      status_conditions << overdue_condition  if @rule.include_overdue?
      status_conditions << due_soon_condition if @rule.include_due_soon?

      conditions = status_conditions.dup
      conditions << recently_updated_condition if @rule.include_recently_updated?
      conditions << recently_created_condition if @rule.include_recently_created?

      return scope if conditions.empty?

      scope = scope.joins(:status) if status_conditions.any?
      scope.where(conditions.reduce(:or))
    end

    # Cumulative "since last run" narrowing. The two flags are independent and
    # OR-combined: created-only, updated-only, or both (checking both reproduces
    # the legacy single-flag behaviour). The cutoff is the last successful run
    # (falling back to the rule's creation time on the very first run).
    def apply_since_last_run_filter(scope)
      t = Issue.table_name
      conditions = []
      conditions << "#{t}.created_on > :cutoff" if @rule.since_last_run_created?
      conditions << "#{t}.updated_on > :cutoff" if @rule.since_last_run_updated?
      return scope if conditions.empty?

      cutoff = @rule.last_success_at || @rule.created_at
      return scope if cutoff.nil?

      scope.where(conditions.join(' OR '), cutoff: cutoff)
    end

    def apply_personalization_filters(scope)
      return scope unless @user

      scope = apply_source_personalization(scope)
      scope = apply_flag_personalization(scope)
      scope
    end

    # Source-aware narrowing (spec §7.4): when a recipient was selected because
    # they are an assignee/author/watcher of matching issues, their digest is
    # limited to the issues backing that relationship. Multiple source modes are
    # OR-combined (e.g. assignee OR watcher). A recipient selected via any broad
    # mode (project members, role, specific user, email) gets the full matching
    # list, so no source narrowing is applied.
    def apply_source_personalization(scope)
      modes = @recipient_modes
      return scope if modes.blank?
      return scope if modes.include?(:broad)

      issues = Issue.arel_table
      conditions = []
      conditions << issues[:assigned_to_id].eq(@user.id) if modes.include?(:assignees)
      conditions << issues[:author_id].eq(@user.id)      if modes.include?(:authors)
      if modes.include?(:watchers)
        watched = Watcher.where(watchable_type: 'Issue', user_id: @user.id).select(:watchable_id)
        conditions << issues[:id].in(watched.arel)
      end
      return scope if conditions.empty?

      scope.where(conditions.reduce(:or))
    end

    # Explicit personalization toggles, independent of recipient_modes
    # (spec §7.4). AND-combined: each checked flag narrows the scope further.
    def apply_flag_personalization(scope)
      scope = scope.where(assigned_to_id: @user.id) if @rule.filter_assigned_to_recipient?

      if @rule.filter_watched_by_recipient?
        watcher_ids = Watcher.where(watchable_type: 'Issue', user_id: @user.id).select(:watchable_id)
        scope = scope.where(id: watcher_ids)
      end

      scope = scope.where(author_id: @user.id) if @rule.filter_authored_by_recipient?

      scope
    end

    def portable_due_date_order_sql
      table = Issue.table_name
      # `NULLS LAST` is PostgreSQL-specific. Ordering by the boolean IS NULL
      # expression first is supported by PostgreSQL, MySQL, and SQLite and keeps
      # undated issues after dated issues on every supported Redmine database.
      "#{table}.due_date IS NULL ASC, #{table}.due_date ASC, #{table}.id ASC"
    end

    def open_condition
      IssueStatus.arel_table[:is_closed].eq(false)
    end

    def closed_condition
      IssueStatus.arel_table[:is_closed].eq(true)
    end

    def overdue_condition
      issues = Issue.arel_table
      statuses = IssueStatus.arel_table
      min_days = @rule.overdue_min_days.to_i
      cutoff = min_days > 0 ? issues[:due_date].lteq(Date.current - min_days.days) \
                             : issues[:due_date].lt(Date.current)
      statuses[:is_closed].eq(false)
        .and(issues[:due_date].not_eq(nil))
        .and(cutoff)
    end

    def due_soon_condition
      days = @rule.due_soon_days.to_i
      issues = Issue.arel_table
      statuses = IssueStatus.arel_table
      statuses[:is_closed].eq(false)
        .and(issues[:due_date].not_eq(nil))
        .and(issues[:due_date].gteq(Date.current))
        .and(issues[:due_date].lteq(Date.current + days.days))
    end

    def recently_updated_condition
      days = @rule.recently_updated_days.to_i
      Issue.arel_table[:updated_on].gteq(days.days.ago)
    end

    def recently_created_condition
      days = @rule.recently_created_days.to_i
      Issue.arel_table[:created_on].gteq(days.days.ago)
    end
  end
end
