# frozen_string_literal: true

module IssueDigest
  class IssueResolver
    def initialize(rule, user: nil)
      @rule = rule
      @user = user
    end

    # Returns a scoped relation of issues visible to @user matching the rule's filters.
    # When user is nil (used for candidate scope in RecipientResolver), returns
    # Issue.visible (system-wide visible) scoped to the project — no per-user filter.
    def resolve
      build_scope
    rescue StandardError => e
      Rails.logger.error "[IssueDigest] Rule ##{@rule.id}: issue resolution failed: #{e.class}: #{e.message}"
      Issue.none
    end

    # Base scope without visibility applied — used by RecipientResolver to find
    # candidate assignees/watchers without loading issues into memory.
    def base_scope
      if @user
        # Per-user delivery path: respect Redmine's full visibility rules.
        # Issue.visible already joins :project internally; do not double-join.
        scope = Issue.visible(@user)
      else
        # Candidate-scope path (recipient discovery, rake context).
        # Issue.visible(User.current) resolves to AnonymousUser in rake, which
        # sees only public projects — private projects return zero issues, making
        # assignees/authors/watchers modes silently produce 0 recipients.
        # Skip visibility here; per-recipient filtering is enforced in #resolve
        # (called with a real user) at delivery time.
        scope = Issue.joins(:project)
                     .where("#{Project.table_name}.status != ?", Project::STATUS_ARCHIVED)
      end
      if @rule.include_subprojects?
        scope = scope.where(
          "#{Project.table_name}.lft >= ? AND #{Project.table_name}.rgt <= ?",
          @rule.project.lft, @rule.project.rgt
        )
      else
        scope = scope.where("#{Issue.table_name}.project_id = ?", @rule.project.id)
      end
      scope
    end

    private

    def build_scope
      scope = base_scope
      scope = apply_status_filters(scope)
      scope = apply_date_filters(scope)
      scope = apply_since_last_run_filter(scope)
      scope = apply_personalization_filters(scope)
      adapter = IssueDigest::QueryAdapter.new(@rule)
      scope   = adapter.apply_to(scope)
      @query_adapter_warning = adapter.warning
      scope = scope.order(Arel.sql("#{Issue.table_name}.due_date ASC NULLS LAST, #{Issue.table_name}.id ASC"))
      scope
    end

    public

    # Returns any warning generated by the QueryAdapter (e.g. deleted query).
    # Only populated after #resolve or #base_scope is called via build_scope.
    def query_adapter_warning
      @query_adapter_warning
    end

    private

    def apply_status_filters(scope)
      open   = @rule.include_open?
      closed = @rule.include_closed?

      # Build status conditions
      conditions = []
      conditions << open_condition   if open
      conditions << closed_condition if closed
      conditions << overdue_condition if @rule.include_overdue?
      conditions << due_soon_condition if @rule.include_due_soon?

      return scope if conditions.empty?

      # If both open and closed are selected → no status filter (all statuses)
      return scope if open && closed && !@rule.include_overdue? && !@rule.include_due_soon?

      scope.joins(:status).where(conditions.reduce(:or))
    end

    def apply_date_filters(scope)
      scope = scope.where(recently_updated_condition) if @rule.include_recently_updated?
      scope = scope.where(recently_created_condition) if @rule.include_recently_created?
      scope
    end

    def apply_since_last_run_filter(scope)
      return scope unless @rule.only_since_last_run?

      cutoff = @rule.last_success_at || @rule.created_at
      return scope if cutoff.nil?

      t = Issue.table_name
      scope.where("#{t}.created_on > ? OR #{t}.updated_on > ?", cutoff, cutoff)
    end

    def apply_personalization_filters(scope)
      return scope unless @user

      scope = scope.where(assigned_to_id: @user.id) if @rule.filter_assigned_to_recipient?

      if @rule.filter_watched_by_recipient?
        watcher_ids = Watcher.where(watchable_type: 'Issue', user_id: @user.id).select(:watchable_id)
        scope = scope.where(id: watcher_ids)
      end

      scope = scope.where(author_id: @user.id) if @rule.filter_authored_by_recipient?

      scope
    end

    def open_condition
      IssueStatus.arel_table[:is_closed].eq(false)
    end

    def closed_condition
      IssueStatus.arel_table[:is_closed].eq(true)
    end

    def overdue_condition
      issues = Issue.arel_table
      statuses = IssueStatus.arel_table
      min_days = @rule.overdue_min_days.to_i
      cutoff = min_days > 0 ? issues[:due_date].lteq(Date.current - min_days.days) \
                             : issues[:due_date].lt(Date.current)
      statuses[:is_closed].eq(false)
        .and(issues[:due_date].not_eq(nil))
        .and(cutoff)
    end

    def due_soon_condition
      days = @rule.due_soon_days.to_i
      issues = Issue.arel_table
      statuses = IssueStatus.arel_table
      statuses[:is_closed].eq(false)
        .and(issues[:due_date].not_eq(nil))
        .and(issues[:due_date].gteq(Date.current))
        .and(issues[:due_date].lteq(Date.current + days.days))
    end

    def recently_updated_condition
      days = @rule.recently_updated_days.to_i
      "#{Issue.table_name}.updated_on >= #{ActiveRecord::Base.connection.quote(days.days.ago)}"
    end

    def recently_created_condition
      days = @rule.recently_created_days.to_i
      "#{Issue.table_name}.created_on >= #{ActiveRecord::Base.connection.quote(days.days.ago)}"
    end
  end
end
